# numpy 실습

In [1]:
import numpy as np

In [2]:
np.__version__

'2.2.6'

## numpy객체 생성

In [7]:
# 리스트 -> ndarray

a = [1,2,3,4,5]
arr = np.array(a)
arr

array([1, 2, 3, 4, 5])

In [11]:
type(arr)

numpy.ndarray

In [12]:
len(arr)

5

In [13]:
# 튜플 -> ndarray

a = (1,2,3,4,5)
arr = np.array(a)
arr

array([1, 2, 3, 4, 5])

In [15]:
arr.size

5

In [16]:
arr.dtype

dtype('int64')

In [19]:
a = [1.0,2,3,4,5]
arr = np.array(a)
arr

array([1., 2., 3., 4., 5.])

In [20]:
arr.dtype

dtype('float64')

## 2차원 데이터 만들기

In [21]:
a2d = [[1,2,3],[4,5,6],[7,8,9]]
a2d

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [22]:
np.array(a2d)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
a2d = [[1,2,3],[4,5,6],[7,8,9]]
a2d

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [33]:
a2d = np.array(a2d)
a2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
len(a2d)

3

In [35]:
a2d.size

9

In [36]:
a2d.dtype

dtype('int64')

In [38]:
a2d.shape

(3, 3)

## numpy 객체 저장 및 로딩

In [39]:
a2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [40]:
np.save('first_array', a2d)

In [42]:
a2d_load = np.load('first_array.npy')
a2d_load

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## BUILT-IN METHODS AND FUNCTIONS

In [43]:
np.zeros(4)

array([0., 0., 0., 0.])

In [44]:
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [45]:
# 1차원
np.ones((7,))

array([1., 1., 1., 1., 1., 1., 1.])

In [46]:
# 2차원
np.ones((4,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

## 특정 값으로 행렬 만들기

In [47]:
# np.full(shape, 특정값)
np.full((7,), 5)

array([5, 5, 5, 5, 5, 5, 5])

In [48]:
np.full((7,2), 5)

array([[5, 5],
       [5, 5],
       [5, 5],
       [5, 5],
       [5, 5],
       [5, 5],
       [5, 5]])

In [49]:
np.full((4,2,3), 5)

array([[[5, 5, 5],
        [5, 5, 5]],

       [[5, 5, 5],
        [5, 5, 5]],

       [[5, 5, 5],
        [5, 5, 5]],

       [[5, 5, 5],
        [5, 5, 5]]])

## 정수의 배열을 얻고자 할때

In [50]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [51]:
# numpy로 표현하기
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
np.arange(5,30+1)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29, 30])

In [55]:
# np.arange(start, stop, step)
np.arange(1,12,2)

array([ 1,  3,  5,  7,  9, 11])

## 실수를 얻고자 할때

In [56]:
# lin -> liner : 실수 값
# np.linspace(start, end, 갯수)
np.linspace(0, 20, 15)

array([ 0.        ,  1.42857143,  2.85714286,  4.28571429,  5.71428571,
        7.14285714,  8.57142857, 10.        , 11.42857143, 12.85714286,
       14.28571429, 15.71428571, 17.14285714, 18.57142857, 20.        ])

In [57]:
np.linspace(0,20,4)

array([ 0.        ,  6.66666667, 13.33333333, 20.        ])

In [58]:
# reshape
arr = np.arange(1,21+1)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21])

In [59]:
arr2d = arr.reshape(3,7)
arr2d

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21]])

In [60]:
arr2d.shape

(3, 7)

In [62]:
arr2d.size

21

In [63]:
arr2d = arr.reshape(7,3)

In [64]:
arr2d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

In [65]:
arr1d = arr2d.reshape(21)
arr1d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21])

In [66]:
arr2d =arr1d.reshape(-1, 3)   # 이게 모지?
arr2d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

In [69]:
arr1d.reshape(3,-1)    # -1은 차원을 자동추론하는 기능.

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21]])

In [70]:
arr2d.max()

np.int64(21)

In [71]:
arr2d.min()

np.int64(1)

In [72]:
arr2d.sum()

np.int64(231)

In [73]:
arr2d.mean()

np.float64(11.0)

In [74]:
arr.std()

np.float64(6.0553007081949835)

In [75]:
arr.var()

np.float64(36.666666666666664)

## 다차원 배열로 한번에 만들기

In [76]:
np.arange(5,20).reshape(3,5)

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

## 랜덤값으로 채워진 배열을 만들 수 있다.

In [78]:
import random

In [156]:
random.random()

0.7141294836112025

In [80]:
# 파이썬의 기본 랜덤 라이브러리는 다차원 배열이 안됨
# 랜덤으로 5개의 숫자 만들기.

In [82]:
np.random.random(5)

array([0.23475982, 0.5431654 , 0.06972392, 0.87363259, 0.54992442])

In [83]:
np.random.random((5,))

array([0.82456048, 0.79862964, 0.70159562, 0.10262094, 0.41278813])

- random seed

In [84]:
# 0~1사이의 실수로 난수 발생
np.random.random((3,5))

array([[0.11255681, 0.05133963, 0.11358504, 0.84786735, 0.6325904 ],
       [0.62547207, 0.82500936, 0.08171233, 0.2293846 , 0.75938592],
       [0.91958127, 0.88028941, 0.703125  , 0.37216058, 0.31754595]])

In [126]:
random.seed(3)
random.random()

0.23796462709189137

In [ ]:
# random.seed(3)
# 랜덤으로 뽑는 숫자가 나오는 패턴을 일치시키는 방법
# 첫번째 실행에 나온숫자, 두번째 실행에 나온숫자, ... => 패턴
# 하나의 셀에만 적용

In [175]:
np.random.seed(3)
np.random.random((3,5))

array([[0.5507979 , 0.70814782, 0.29090474, 0.51082761, 0.89294695],
       [0.89629309, 0.12558531, 0.20724288, 0.0514672 , 0.44080984],
       [0.02987621, 0.45683322, 0.64914405, 0.27848728, 0.6762549 ]])

In [237]:
np.random.seed(2)
np.random.random((3,5))


array([[0.4359949 , 0.02592623, 0.54966248, 0.43532239, 0.4203678 ],
       [0.33033482, 0.20464863, 0.61927097, 0.29965467, 0.26682728],
       [0.62113383, 0.52914209, 0.13457995, 0.51357812, 0.18443987]])

## np.random.randint(start, stop, size = shape)
시작값과 끝값을 줄 수 있다.

In [238]:
np.random.seed(9)

In [239]:
np.random.randint(1, 45, (7,))

array([29, 23,  2, 23, 41, 28, 34], dtype=int32)

In [242]:
np.random.randint(1, 45, (3,4))

array([[41,  5, 36,  1],
       [11, 17,  5,  6],
       [25, 20, 31, 41]], dtype=int32)

In [241]:
np.random.randint(1, 45, (3,4))

array([[12, 38, 20, 39],
       [10, 17, 41, 14],
       [34, 14, 30, 23]], dtype=int32)

In [245]:
# 1~9+1
X = np.random.randint(1, 100, (3,4))

In [243]:
# 데이터 전체에서 최대값, 최소값, 전체합, 전체평균, 표준편차, 중앙값을 구하세요

In [246]:
X.max()

np.int32(92)

In [247]:
X.min()

np.int32(2)

In [248]:
X.mean()

np.float64(48.5)

In [249]:
X.std()

np.float64(29.107559155655768)

In [250]:
X.var()

np.float64(847.25)

In [251]:
a = np.array([3,4,5,6,7,8,9,10])
sorted(a.tolist())

[3, 4, 5, 6, 7, 8, 9, 10]

In [252]:
type(a)

numpy.ndarray

In [253]:
# 중앙값 => 데이터를 오름차순으로 정렬한 후, 중간에 있는 값
# 넘파이 객체에는 median이 없음
# 중앙 값이 두개인 경우는 두 값의 평균을 구함.

np.median(a)

np.float64(6.5)

In [254]:
np.random.seed(3)
X = np.random.randint(1, 100, (4,5))
X

array([[25,  4, 57, 73,  1],
       [22, 20, 75, 42, 11],
       [22, 39, 97, 21, 45],
       [94, 40, 15, 27, 82]], dtype=int32)

axis = 0 : 행 인덱스가 증가하는 방향
axis = 1 : 열 인덱스가 증가하는 방향

In [255]:
# 각 열별 최대 값을 구하고 싶다.
# [94, 40, 97, 73, 82]
# 가장 큰 값을 구해야 하는 경우

X.max(axis=0)

array([94, 40, 97, 73, 82], dtype=int32)

In [256]:
# 각 행별 최대 값을 구하고 싶다.
# [73, 75, 97, 94]
# 가장 큰 값을 구해야 하는 경우

X.max(axis=1)

array([73, 75, 97, 94], dtype=int32)

In [257]:
X

array([[25,  4, 57, 73,  1],
       [22, 20, 75, 42, 11],
       [22, 39, 97, 21, 45],
       [94, 40, 15, 27, 82]], dtype=int32)

- 비교

In [258]:
# 원하는 데이터의 갯수를 구하는 방법
# X에서 70보다 큰 데이터는 몇개?
X>70

array([[False, False, False,  True, False],
       [False, False,  True, False, False],
       [False, False,  True, False, False],
       [ True, False, False, False,  True]])

In [259]:
(X>70).sum()

np.int64(5)

In [260]:
# X에서 70보다 큰 데이터들만 가져와
X[X > 70]

array([73, 75, 97, 94, 82], dtype=int32)

In [261]:
X[X>70].size

5

## [실습]
- 4x4 ndarray를 만드세요
- 단, 2에서 32까지 순차적 짝수로 채워지도록 하세요.

In [264]:
X = np.arange(2,32+1,2).reshape(4,-1)

In [265]:
X

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24],
       [26, 28, 30, 32]])

## SHAPE, LENGTH AND TYPE OF NUMPY ARRAYS

In [266]:
X

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24],
       [26, 28, 30, 32]])

In [267]:
X.shape

(4, 4)

In [268]:
X.size

16

In [269]:
X.dtype

dtype('int64')

## SHAPE, LENGTH AND TYPE OF NUMPY ARRAYS

In [270]:
X.max()

np.int64(32)

In [271]:
X.min()

np.int64(2)

In [272]:
np.random.seed(3)
X = np.random.randint(1, 100, (4,5))
X

array([[25,  4, 57, 73,  1],
       [22, 20, 75, 42, 11],
       [22, 39, 97, 21, 45],
       [94, 40, 15, 27, 82]], dtype=int32)

In [273]:
X.max(axis=0)

array([94, 40, 97, 73, 82], dtype=int32)

In [274]:
X.argmax()

np.int64(12)

In [275]:
X.argmin()

np.int64(4)

In [276]:
# 행별 최대값의 위치? 행이 증가하는 방향
X.argmax(axis=0)

array([3, 3, 2, 0, 3])

In [277]:
# 열별 최대값의 위치? 열이 증가하는 방향
X.argmax(axis=1)

array([3, 2, 2, 0])

## Accessing Elements Into ndarrays

In [278]:
x = np.random.randint(1,100,7)
x

array([91, 23, 67,  3, 64, 61,  2], dtype=int32)

In [279]:
x[2]

np.int32(67)

In [280]:
x[-1]

np.int32(2)

### 다차원배열의 인덱스 접근

In [281]:
X

array([[25,  4, 57, 73,  1],
       [22, 20, 75, 42, 11],
       [22, 39, 97, 21, 45],
       [94, 40, 15, 27, 82]], dtype=int32)

In [282]:
# 2행 3열 위치 데이터를 가져오시오.
X[1][2]

np.int32(75)

In [283]:
# numpy에서는 다음과 같이 표현할 수 있음
X[1, 2]

np.int32(75)

In [284]:
X[3,4]

np.int32(82)

## Slicing - 잘라서 가져오기
- 1. ndarray[start:end]
- 2. ndarray[start:]
- 3. ndarray[:end]

In [285]:
X

array([[25,  4, 57, 73,  1],
       [22, 20, 75, 42, 11],
       [22, 39, 97, 21, 45],
       [94, 40, 15, 27, 82]], dtype=int32)

In [286]:
# 슬라이싱 데이터 : [25,  4, 57]
X[0, :3]

array([25,  4, 57], dtype=int32)

In [287]:
# [[22, 39, 97], 
#  [94, 40, 15]]

X[2: , :2+1]

array([[22, 39, 97],
       [94, 40, 15]], dtype=int32)

In [ ]:
# 데이터 억세스 기호는 대괄호 [, ] => 콤마의 왼쪽은 행자리, 오른쪽은 열자리.
# 행자리도 : 을 사용,
# 열자리도 : 을 사용할 수 있음

In [288]:
X

array([[25,  4, 57, 73,  1],
       [22, 20, 75, 42, 11],
       [22, 39, 97, 21, 45],
       [94, 40, 15, 27, 82]], dtype=int32)

In [289]:
# 20, 75
# 39, 97
# 40, 15
# 값 가져오기
X[1:3+1, 1:2+1]

array([[20, 75],
       [39, 97],
       [40, 15]], dtype=int32)

In [290]:
# 57, 73, 1
# 75, 42, 11

X[:1+1, 2:]

array([[57, 73,  1],
       [75, 42, 11]], dtype=int32)

## 실습
- X = 5 x 5 ndarray 를 만드세요.정수 1 부터 25 까지 순차적으로 들어있습니다.
- Y = Boolean indexing 을 이용해서 홀수만 뽑아서 배열로 만듭니다.

In [291]:
X = np.arange(1, 26).reshape(-1,5)
X

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [292]:
Y = X[X % 2 == 1]
Y

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25])

## Arithmetic operations and Broadcasting
 1차원 배열 연산

In [295]:
x

array([91, 23, 67,  3, 64, 61,  2], dtype=int32)

In [296]:
#  학생들 수학점수가 있다.
score_list = [77, 46, 55, 99, 87, 81]
score_list

[77, 46, 55, 99, 87, 81]

In [297]:
# 각 학생의 점수를 7점씩 빼야 한다.
new_score_list =[]
for score in score_list:
    new_score_list.append(score - 7)
new_score_list

[70, 39, 48, 92, 80, 74]

In [298]:
# numpy 방법, 브로드캐스팅
np.array(score_list) - 7 

array([70, 39, 48, 92, 80, 74])

In [299]:
x

array([91, 23, 67,  3, 64, 61,  2], dtype=int32)

In [300]:
x-10

array([81, 13, 57, -7, 54, 51, -8], dtype=int32)

In [301]:
x // 2

array([45, 11, 33,  1, 32, 30,  1], dtype=int32)

## 2차원 배열 연산

In [302]:
X

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [303]:
X*2

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40],
       [42, 44, 46, 48, 50]])

In [304]:
X+10

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [305]:
X//2

array([[ 0,  1,  1,  2,  2],
       [ 3,  3,  4,  4,  5],
       [ 5,  6,  6,  7,  7],
       [ 8,  8,  9,  9, 10],
       [10, 11, 11, 12, 12]])