# 문제 1 

slicing 문제 : 다음의 데이터를 추철하는 하는 코드를 작성하시오.
datas = [[40, 20, 75, 42, 11],
       [30, 39, 92, 21, 45],
       [94, 40, 15, 27, 82]]

arr = np.array(datas)
arr
---------------------
# 출력 결과: 
array([11, 45, 82])

In [95]:
datas = [[40, 20, 75, 42, 11],
       [30, 39, 92, 21, 45],
       [94, 40, 15, 27, 82]]
arr=np.array(datas)
arr[:,-1]

array([11, 45, 82])

In [100]:
arr = np.array(datas)
arr2 = []
for line in arr:
    arr2.append(line[-1])
np.array(arr2)

array([11, 45, 82])

In [9]:
np.array(arr2)

array([11, 45, 82])

## 문제2

# numpy함수를 이용하여 10이하의 짝수와 홀수 각각의 리스트를 생성하고, 이 두가지 리스트를 사용하여 2차원의 데이터를 만들어라.

---------------------
# 출력 결과: 
array([[ 1,  3,  5,  7,  9],
       [ 2,  4,  6,  8, 10]])

In [26]:
X = np.arange(10+1)
X

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
Y = X[X%2 == 0]


In [20]:
Z = X[X%2 ==1]
Z

array([1, 3, 5, 7, 9])

array([ 3,  7, 11, 15, 19])

# 문제 3
-10부터 30까지 정수로 이루어진 1차원배열을 만든다음 2차원  (7, -1) 형태로 변환하시오.

그리고 최댓값과 최솟값을 구하시오.

In [29]:
a = np.arange(10,30+1)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30])

In [30]:
a.max()

np.int64(30)

In [31]:
a.min()

np.int64(10)

# 문제4
- 문제: 위 배열을 3행 4열 형태로 reshape 하시오. 변환된 배열에서 마지막 행만 출력하시오.

In [37]:
datas = [[10, 20, 30, 40, 50, 60],
         [70, 80, 90, 100, 110, 120]]

np.array(datas).reshape(3,4)

array([[ 10,  20,  30,  40],
       [ 50,  60,  70,  80],
       [ 90, 100, 110, 120]])

# 문제 5
- 코드와 그  출력값이 다음과 같을 때 0.6664104711248381을 출력하는 코드를 작성하시오.

In [40]:
import random

In [52]:
random.seed(12)
print(random.random())
print(random.random())
print(random.random())

0.4745706786885481
0.6574725026572553
0.6664104711248381


## 문제 6
- seed값을 5로 고정한 후 random.randint(1,11)을 세번 실행했을 때 나오는 값을 구하시오.

In [53]:
random.seed(5)
random.randint(1,11)
random.randint(1,11)
print(random.randint(1,11))

6


## 문제 7

(1) 1~25까지 step이 3개인 1차원의 배열을 만들고,
(2) reshape을 이용하여 3x3행렬로 만드시오.
----------------------
출력결과
(1)
array([ 1,  4,  7, 10, 13, 16, 19, 22, 25])
(2) 
array([[ 1,  4,  7],
       [10, 13, 16],
       [19, 22, 25]])

In [67]:
a = list(range(1,25+1,3))
a

[1, 4, 7, 10, 13, 16, 19, 22, 25]

In [69]:
np.array(a).reshape(3,3)

array([[ 1,  4,  7],
       [10, 13, 16],
       [19, 22, 25]])

# 문제 8

arr의 각 행에서 최댓값만 추출하여 1차원 배열 형태로 출력하시오.
---------------------
import numpy as np

np.random.seed(11)
arr = np.random.random((4, 5))

In [72]:
np.random.seed(11) 
arr = np.random.random((4, 5))
arr

array([[0.18026969, 0.01947524, 0.46321853, 0.72493393, 0.4202036 ],
       [0.4854271 , 0.01278081, 0.48737161, 0.94180665, 0.85079509],
       [0.72996447, 0.10873607, 0.89390417, 0.85715425, 0.16508662],
       [0.63233401, 0.02048361, 0.11673727, 0.31636731, 0.15791231]])

In [73]:
arr.max(axis=1)

array([0.72493393, 0.94180665, 0.89390417, 0.63233401])

# 문제 9

np.random.randint(1, 45, (3,4))를 출력하고 리스트 형태로 변환하여 출력하시오.
----------------
결과값 예시: [[2, 27, 6, 41], [27, 23, 3, 3], [34, 30, 43, 25]]


In [75]:
X = np.random.randint(1, 45, (3,4))
X

array([[16, 33, 24, 28],
       [ 7, 26, 44, 11],
       [28, 15,  8, 16]], dtype=int32)

In [80]:
X.tolist()

[[16, 33, 24, 28], [7, 26, 44, 11], [28, 15, 8, 16]]

## 문제 10
reshape 함수를 사용해 1부터 30까지의 숫자 중 짝수를 찾아 (3,5)의 행렬로 만드시오.
------------------------------
array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30]])

In [83]:
A = list(range(1,30+1))

In [90]:
A = np.array(A)
A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [92]:
A[A%2 == 0].reshape(3,5)

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30]])

# 문제 11

#range을 이용하여 1~20까지 숫자를 나열한 후 4행 5형로 정렬하고 그 중 각 행의 최소값을 추출하시오
---------------------
array([1, 2, 3, 4, 5]) 


In [94]:
np.arange(1,21).reshape(4,5).min(axis=1)

array([ 1,  6, 11, 16])